/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import com.toedter.calendar.JCalendar;
import java.awt.print.Printable;
import java.sql.*;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import java.awt.*;
import java.awt.print.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import com.toedter.calendar.JCalendar.*;
import java.text.DateFormat;
import javax.swing.JPanel;
import java.text.SimpleDateFormat;



/**
 *
 * @author jeissoncc
 */
public class jpagenda extends javax.swing.JPanel implements Printable {
    SqlUsuarios con = new SqlUsuarios();
    conexion conn;
    
    public jpagenda() {
        initComponents();
        
        btprint.setVisible(false);
        
        ///this.jComboBox1.setModel(con.servicios());
        String ids = con.generarNumeroVisita();
        int id_visitas = Integer.parseInt(ids);
        id_visitas = id_visitas + 1;
        String idv = String.valueOf(id_visitas);
        txtconsecutivo.setText(idv);
        
        conexion_consulta.conectar();
        JComboBox jcb = new JComboBox(con.servicios());
        TableColumn tc = jtagendaserv.getColumnModel().getColumn(0);
        TableCellEditor tce = new DefaultCellEditor(jcb);
        tc.setCellEditor(tce);
        
        Calendar fecha = new GregorianCalendar();                                                   
        int ano = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        txtfechaactual.setText(""+ano+"-"+(mes+1)+"-"+dia+"");
    }
    
    private void limpiar() {
            
            txtid.setText("");
            txtfechaactual.setText("");
            txtconsecutivo.setText("");
            txtconsecutivo.setText("");
            txtobservaciones.setText("");
    }
    
    public void mostrar(Clientes r){
        txtcliente.setText(r.getRazon_social());;
        txtcontacto.setText(r.getResponsable());
        txtdireccion.setText(r.getDireccion());
        txttelefono.setText(r.getTelefono());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpagendar = new javax.swing.JPanel();
        lbfecha = new javax.swing.JLabel();
        lbcliente = new javax.swing.JLabel();
        lbid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btbuscar = new javax.swing.JButton();
        lbservicio = new javax.swing.JLabel();
        lbdireccion = new javax.swing.JLabel();
        txtcliente = new javax.swing.JLabel();
        lbtelefono = new javax.swing.JLabel();
        txttelefono = new javax.swing.JLabel();
        lbcontacto = new javax.swing.JLabel();
        txtcontacto = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        etiqueta = new javax.swing.JLabel();
        lbobserva = new javax.swing.JLabel();
        btexit = new javax.swing.JButton();
        btprint = new javax.swing.JButton();
        lbconsecutivo = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtagendaserv = new javax.swing.JTable();
        btsalvar2 = new javax.swing.JButton();
        txtconsecutivo = new javax.swing.JLabel();
        btinsertar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtobservaciones = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtfechaactual = new javax.swing.JLabel();
        txtfechavisita = new com.toedter.calendar.JDateChooser();

        setMinimumSize(new java.awt.Dimension(630, 470));
        setPreferredSize(new java.awt.Dimension(630, 470));
        setSize(new java.awt.Dimension(630, 470));

        jpagendar.setBackground(new java.awt.Color(255, 255, 255));
        jpagendar.setMinimumSize(new java.awt.Dimension(630, 470));
        jpagendar.setPreferredSize(new java.awt.Dimension(630, 470));
        jpagendar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbfecha.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        lbfecha.setText("fecha:");
        jpagendar.add(lbfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, 25));

        lbcliente.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        lbcliente.setText("Cliente:");
        jpagendar.add(lbcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lbid.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        lbid.setText("ID:");
        jpagendar.add(lbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 15, -1, 25));
        lbid.getAccessibleContext().setAccessibleDescription("");

        txtid.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jpagendar.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 15, 110, 25));

        btbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btbuscar.setForeground(new java.awt.Color(51, 182, 215));
        btbuscar.setText("Buscar");
        btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarActionPerformed(evt);
            }
        });
        jpagendar.add(btbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 15, -1, 40));

        lbservicio.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        lbservicio.setText("Servicio:");
        jpagendar.add(lbservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 25));

        lbdireccion.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        lbdireccion.setText("Direccion:");
        jpagendar.add(lbdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtcliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jpagendar.add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 430, 25));

        lbtelefono.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        lbtelefono.setText("Telefono:");
        jpagendar.add(lbtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 64, -1));

        txttelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jpagendar.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 430, 25));

        lbcontacto.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        lbcontacto.setText("Contacto:");
        jpagendar.add(lbcontacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtcontacto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jpagendar.add(txtcontacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 430, 25));
        jpagendar.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 10));
        jpagendar.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 200, 10));

        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("Datos del Servicio");
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpagendar.add(etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 201, -1));

        lbobserva.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        lbobserva.setText("Observaciones:");
        jpagendar.add(lbobserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        btexit.setBackground(new java.awt.Color(255, 255, 255));
        btexit.setForeground(new java.awt.Color(51, 182, 215));
        btexit.setText("Salir");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });
        jpagendar.add(btexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 60, 40));

        btprint.setBackground(new java.awt.Color(255, 255, 255));
        btprint.setForeground(new java.awt.Color(51, 182, 215));
        btprint.setText("Imprimir");
        btprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprintActionPerformed(evt);
            }
        });
        jpagendar.add(btprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 90, 40));

        lbconsecutivo.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        lbconsecutivo.setText("Consecutivo:");
        jpagendar.add(lbconsecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 15, -1, 25));

        txtdireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jpagendar.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 430, 25));

        jtagendaserv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Servicio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtagendaserv);

        jpagendar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 480, 70));

        btsalvar2.setBackground(new java.awt.Color(255, 255, 255));
        btsalvar2.setForeground(new java.awt.Color(51, 182, 215));
        btsalvar2.setText("Guardar");
        btsalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvar2ActionPerformed(evt);
            }
        });
        jpagendar.add(btsalvar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 80, 40));

        txtconsecutivo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtconsecutivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtconsecutivo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtconsecutivo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpagendar.add(txtconsecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 15, 90, 25));

        btinsertar.setBackground(new java.awt.Color(255, 255, 255));
        btinsertar.setForeground(new java.awt.Color(51, 182, 215));
        btinsertar.setText("Insertar");
        btinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinsertarActionPerformed(evt);
            }
        });
        jpagendar.add(btinsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 90, 40));

        txtobservaciones.setColumns(20);
        txtobservaciones.setRows(5);
        jScrollPane2.setViewportView(txtobservaciones);

        jpagendar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 570, 60));

        jLabel1.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        jLabel1.setText("Fecha Visita:");
        jpagendar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 25));

        txtfechaactual.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtfechaactual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtfechaactual.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtfechaactual.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jpagendar.add(txtfechaactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 15, 120, 25));

        txtfechavisita.setDateFormatString("yyyy-MM-dd");
        jpagendar.add(txtfechavisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 230, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpagendar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpagendar, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
         conexion_consulta modSql  = new conexion_consulta();
        
        String id_cliente = txtid.getText();
        Clientes r;
        r= modSql.existeCliente(id_cliente);
        if(r==null){
        
        }else{
            mostrar(r);
        }
    }//GEN-LAST:event_btbuscarActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btexitActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btsalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvar2ActionPerformed
        SqlUsuarios modSql  = new SqlUsuarios();
            VisitasAgenda    mod     = new VisitasAgenda(); 
            
            String ids = new String(txtid.getText());
            String fecha = new String(txtfechaactual.getText());           
            String consecutivo = new String(txtconsecutivo.getText()); 
            int vanio = txtfechavisita.getCalendar().get(Calendar.YEAR);
            int vmes = txtfechavisita.getCalendar().get(Calendar.MONTH);
            int vdia = txtfechavisita.getCalendar().get(Calendar.DAY_OF_MONTH);
            String fechaVisita = vanio+"-"+vmes+"-"+vdia;
            
            String servicio = new String(txtconsecutivo.getText()); 
            String observaciones = new String(txtobservaciones.getText()); 
            String estado = new String("Agendada"); 
            
            int id = Integer.parseInt(ids);
            int consec = Integer.parseInt(consecutivo);
            
           
            mod.setId_cliente(id);
            mod.setId_visita(consec);
            mod.setFecha(fecha);
            mod.setFechavisita(fechaVisita);
            mod.setObservaciones(observaciones);
            mod.setEstado(estado);
           
            
            modSql.registrarVisita(mod);
            
            
            JOptionPane.showMessageDialog(null, "se ha guardado correctamente la visita: "+ consecutivo);
            btprint.setVisible(true);
    }//GEN-LAST:event_btsalvar2ActionPerformed

    private void btprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprintActionPerformed
        try{
                    PrinterJob gap = PrinterJob.getPrinterJob();
                    gap.setPrintable(this);
                    boolean top = gap.printDialog();
                    if(top){
                        gap.print();
                        
                    }
                }
                catch(PrinterException pex){
                    JOptionPane.showMessageDialog(null, "Error de Programa","Error\n"+pex, JOptionPane.INFORMATION_MESSAGE );
                    
                }
        limpiar();
    }//GEN-LAST:event_btprintActionPerformed

    private void btinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinsertarActionPerformed
        DefaultTableModel temp = (DefaultTableModel) jtagendaserv.getModel();
        Object nuevo[]= {" "};
        temp.addRow(nuevo);
    }//GEN-LAST:event_btinsertarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbuscar;
    private javax.swing.JButton btexit;
    private javax.swing.JButton btinsertar;
    private javax.swing.JButton btprint;
    private javax.swing.JButton btsalvar2;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpagendar;
    private javax.swing.JTable jtagendaserv;
    private javax.swing.JLabel lbcliente;
    private javax.swing.JLabel lbconsecutivo;
    private javax.swing.JLabel lbcontacto;
    private javax.swing.JLabel lbdireccion;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lbid;
    private javax.swing.JLabel lbobserva;
    private javax.swing.JLabel lbservicio;
    private javax.swing.JLabel lbtelefono;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel txtcliente;
    private javax.swing.JLabel txtconsecutivo;
    private javax.swing.JLabel txtcontacto;
    private javax.swing.JLabel txtdireccion;
    private javax.swing.JLabel txtfechaactual;
    private com.toedter.calendar.JDateChooser txtfechavisita;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextArea txtobservaciones;
    private javax.swing.JLabel txttelefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int index) throws PrinterException {
        if(index>0)
        {
            return NO_SUCH_PAGE;
        }
        Graphics2D hub = (Graphics2D) graphics;
        hub.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
        hub.scale(pageFormat.getImageableWidth() / this.getWidth(), pageFormat.getImageableHeight() / this.getHeight());
        btbuscar.setVisible(false);
        btinsertar.setVisible(false);
        btexit.setVisible(false);
        btprint.setVisible(false);
        btsalvar2.setVisible(false);
        this.printAll(hub);
        btbuscar.setVisible(true);
        btinsertar.setVisible(true);
        btexit.setVisible(true);
        btprint.setVisible(true);
        btsalvar2.setVisible(true);
        
        return PAGE_EXISTS;
    }
}
