/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.*;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.TableColumn;
import org.jfree.data.category.DefaultCategoryDataset;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;

/**
 *
 * @author jeissoncc
 */
public class jpdash extends javax.swing.JPanel {
  
    conexion conn;
    PreparedStatement st;
    ResultSet rs;
    ResultSetMetaData rsm;
    DefaultTableModel dfm;
    
    JFreeChart Grafica;
    DefaultCategoryDataset Datos =new DefaultCategoryDataset();
    /**
     * Creates new form jpdash
     */
    public jpdash() {
        initComponents();
        jpanetabla.setVisible(false);
        jplistaagenda.setVisible(false);
        jplistafacturas.setVisible(false);
        
        btlistarcan1.setText("Listar Visitas"+"\n"+"canceladas");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btlistaagendadas = new javax.swing.JButton();
        btlistarcan1 = new javax.swing.JButton();
        btlistafacturadas = new javax.swing.JButton();
        jpanetabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtvisitascan = new javax.swing.JTable();
        jplistaagenda = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtvisitasagen = new javax.swing.JTable();
        jplistafacturas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfacturas = new javax.swing.JTable();
        btsalir = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(630, 470));
        setSize(new java.awt.Dimension(630, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(630, 470));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btlistaagendadas.setBackground(new java.awt.Color(255, 255, 255));
        btlistaagendadas.setForeground(new java.awt.Color(51, 182, 215));
        btlistaagendadas.setText("Listar Facturas Generadas");
        btlistaagendadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlistaagendadasActionPerformed(evt);
            }
        });
        jPanel2.add(btlistaagendadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 190, 40));

        btlistarcan1.setBackground(new java.awt.Color(255, 255, 255));
        btlistarcan1.setForeground(new java.awt.Color(51, 182, 215));
        btlistarcan1.setText("Listar Visitas\n Canceladas");
        btlistarcan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlistarcan1ActionPerformed(evt);
            }
        });
        jPanel2.add(btlistarcan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 40));

        btlistafacturadas.setBackground(new java.awt.Color(255, 255, 255));
        btlistafacturadas.setForeground(new java.awt.Color(51, 182, 215));
        btlistafacturadas.setText("Listar Visitas Programadas");
        btlistafacturadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlistafacturadasActionPerformed(evt);
            }
        });
        jPanel2.add(btlistafacturadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 180, 40));

        jpanetabla.setBackground(new java.awt.Color(255, 255, 255));
        jpanetabla.setForeground(new java.awt.Color(255, 255, 255));
        jpanetabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtvisitascan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Especialista", "Observaciones"
            }
        ));
        jScrollPane2.setViewportView(jtvisitascan);

        jpanetabla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 560, 90));

        jPanel2.add(jpanetabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 590, 260));

        jplistaagenda.setBackground(new java.awt.Color(255, 255, 255));
        jplistaagenda.setForeground(new java.awt.Color(255, 255, 255));
        jplistaagenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtvisitasagen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cliente", "Fecha Solicutd", "Fecha Agenda", "Observaciones"
            }
        ));
        jScrollPane5.setViewportView(jtvisitasagen);

        jplistaagenda.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 560, 90));

        jPanel2.add(jplistaagenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 590, 260));

        jplistafacturas.setBackground(new java.awt.Color(255, 255, 255));
        jplistafacturas.setForeground(new java.awt.Color(255, 255, 255));
        jplistafacturas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Factura ID", "Fecha", "Cliente", "Total"
            }
        ));
        jScrollPane1.setViewportView(jtfacturas);

        jplistafacturas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 560, 90));

        jPanel2.add(jplistafacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 590, 260));

        btsalir.setBackground(new java.awt.Color(255, 255, 255));
        btsalir.setForeground(new java.awt.Color(51, 182, 215));
        btsalir.setText("Salir");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirActionPerformed(evt);
            }
        });
        jPanel2.add(btsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 60, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void btlistafacturadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlistafacturadasActionPerformed
      
        jplistaagenda.setVisible(true);
       jpanetabla.setVisible(false);
       jplistafacturas.setVisible(false);
       
       
        try{
            Class.forName("com.mysql.cj.jdbc.result.ResultSetMetaData");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/findegas","root", "");
            st = con.prepareStatement("SELECT id_cliente, fecha, fecha_visita, observaciones FROM visitas");
            rs = st.executeQuery();
            rsm = rs.getMetaData();
            ArrayList<Object[]> data  = new ArrayList<>();
            while(rs.next()){
                Object[] rows = new Object[rsm.getColumnCount()];
                for (int i = 0; i< rows.length; i++){
                    rows[i]=rs.getObject(i+1);
                }
                data.add(rows);
            }
            dfm = (DefaultTableModel) this.jtvisitasagen.getModel();
            for( int i = 0; i < data.size(); i++){
                dfm.addRow(data.get(i));
            }
        }catch(SQLException ex){
            System.err.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpdash.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btlistafacturadasActionPerformed

    private void btlistarcan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlistarcan1ActionPerformed
        jpanetabla.setVisible(true);
        jplistafacturas.setVisible(false);
        jplistaagenda.setVisible(false);
        
        try{
            Class.forName("com.mysql.cj.jdbc.result.ResultSetMetaData");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/findegas","root", "");
            st = con.prepareStatement("SELECT id_vcancelada, fecha, especialista, observaciones FROM visitas_canceladas");
            rs = st.executeQuery();
            rsm = rs.getMetaData();
            ArrayList<Object[]> data  = new ArrayList<>();
            while(rs.next()){
                Object[] rows = new Object[rsm.getColumnCount()];
                for (int i = 0; i< rows.length; i++){
                    rows[i]=rs.getObject(i+1);
                }
                data.add(rows);
            }
            dfm = (DefaultTableModel) this.jtvisitascan.getModel();
            for( int i = 0; i < data.size(); i++){
                dfm.addRow(data.get(i));
            }
        }catch(SQLException ex){
            System.err.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpdash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btlistarcan1ActionPerformed

    private void btlistaagendadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlistaagendadasActionPerformed
        jpanetabla.setVisible(false);
        jplistaagenda.setVisible(false);
        jplistafacturas.setVisible(true);
        
        try{
            Class.forName("com.mysql.cj.jdbc.result.ResultSetMetaData");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/findegas","root", "");
            st = con.prepareStatement("SELECT id_factura, fecha, cliente, total FROM factura");
            rs = st.executeQuery();
            rsm = rs.getMetaData();
            ArrayList<Object[]> data  = new ArrayList<>();
            while(rs.next()){
                Object[] rows = new Object[rsm.getColumnCount()];
                for (int i = 0; i< rows.length; i++){
                    rows[i]=rs.getObject(i+1);
                }
                data.add(rows);
            }
            dfm = (DefaultTableModel) this.jtfacturas.getModel();
            for( int i = 0; i < data.size(); i++){
                dfm.addRow(data.get(i));
            }
        }catch(SQLException ex){
            System.err.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jpdash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btlistaagendadasActionPerformed

    private void btsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlistaagendadas;
    private javax.swing.JButton btlistafacturadas;
    private javax.swing.JButton btlistarcan1;
    private javax.swing.JButton btsalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel jpanetabla;
    private javax.swing.JPanel jplistaagenda;
    private javax.swing.JPanel jplistafacturas;
    private javax.swing.JTable jtfacturas;
    private javax.swing.JTable jtvisitasagen;
    private javax.swing.JTable jtvisitascan;
    // End of variables declaration//GEN-END:variables
}
