/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

/**
 *
 * @author jeissoncc
 */
public class jpinicial extends javax.swing.JPanel {

    /**
     * Creates new form jpinicial
     */
    public jpinicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpfondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbsalirprin = new javax.swing.JButton();

        jpfondo.setBackground(new java.awt.Color(255, 255, 255));
        jpfondo.setPreferredSize(new java.awt.Dimension(690, 650));
        jpfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N
        jpfondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 610, 370));

        jLabel2.setFont(new java.awt.Font("Hiragino Sans", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FINDEGAS");
        jpfondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 650, -1));

        jLabel3.setFont(new java.awt.Font("Hiragino Sans", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvendido al Sistema de Gestion ");
        jpfondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 650, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel4.setText("Universidad Tecnologica");
        jpfondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("De Pereira");
        jpfondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 120, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel6.setText("Laboratorio de Software");
        jpfondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("2020");
        jpfondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 110, -1));

        jbsalirprin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        jbsalirprin.setBorder(null);
        jbsalirprin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirprinActionPerformed(evt);
            }
        });
        jpfondo.add(jbsalirprin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpfondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpfondo, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbsalirprinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirprinActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbsalirprinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbsalirprin;
    private javax.swing.JPanel jpfondo;
    // End of variables declaration//GEN-END:variables
}
