/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

/**
 *
 * @author jeissoncc
 */
public class jpncliente extends javax.swing.JPanel {

    /**
     * Creates new form jpncliente
     */
    public jpncliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btexiteuser = new javax.swing.JButton();
        btsaveepeuser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(630, 470));
        setSize(new java.awt.Dimension(630, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btexiteuser.setBackground(new java.awt.Color(255, 255, 255));
        btexiteuser.setForeground(new java.awt.Color(51, 182, 215));
        btexiteuser.setText("Salir");
        btexiteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexiteuserActionPerformed(evt);
            }
        });
        jPanel3.add(btexiteuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 60, 40));

        btsaveepeuser.setBackground(new java.awt.Color(255, 255, 255));
        btsaveepeuser.setForeground(new java.awt.Color(51, 182, 215));
        btsaveepeuser.setText("Guardar");
        btsaveepeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveepeuserActionPerformed(evt);
            }
        });
        jPanel3.add(btsaveepeuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 80, 40));

        jLabel1.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        jLabel1.setText("Identificación: ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 25));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 25));

        jLabel3.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        jLabel3.setText("Nombres:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 90, 25));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 180, 25));

        jLabel4.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        jLabel4.setText("Apellidos:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, 25));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 210, 25));

        jLabel5.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        jLabel5.setText("Dirección:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 25));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 570, 25));

        jLabel6.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        jLabel6.setText("Telefono");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 25));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 25));

        jLabel7.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        jLabel7.setText("Email:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, 25));
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 410, 25));

        jLabel8.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        jLabel8.setText("Contraseña:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, 25));

        jLabel10.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        jLabel10.setText("Usuario:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 25));
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 150, 25));
        jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 180, 25));

        jLabel11.setFont(new java.awt.Font("Hiragino Sans", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 182, 215));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Adicionar Cliente");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 630, -1));

        jLabel16.setFont(new java.awt.Font("Hiragino Sans", 1, 14)); // NOI18N
        jLabel16.setText("Empresa:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 25));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 570, 25));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 470));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void btexiteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexiteuserActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btexiteuserActionPerformed

    private void btsaveepeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveepeuserActionPerformed

    }//GEN-LAST:event_btsaveepeuserActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btexiteuser;
    private javax.swing.JButton btsaveepeuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
